### ISSUE TITLE
Error: Unrecognized option: 'save-baseline'

### ISSUE THREAD

**Issue by yannham** [boa-dev/criterion-compare-action#20]
The github action fails with the error "Unrecognized option: 'save-baseline'":

```
error: Unrecognized option: 'save-baseline'
error: bench failed
Error: The process 'cargo' failed with exit code 101
    at ExecState._setResult (/home/runner/work/_actions/jasonwilliams/criterion-compare-action/move_to_actions/dist/index.js:1:7880)
    at ExecState.CheckComplete (/home/runner/work/_actions/jasonwilliams/criterion-compare-action/move_to_actions/dist/index.js:1:7442)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/jasonwilliams/criterion-compare-action/move_to_actions/dist/index.js:1:6406)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
Error: Unhanded error:
Error: The process 'cargo' failed with exit code 101
```

The PR where I tried to add this action: https://github.com/tweag/nickel/pull/333/

It seems related to this issue https://github.com/bheisler/criterion.rs/issues/193, but I couldn't extract enough information to see what would be the fix.

**Comment by yannham** [comment]
This seems to be a [criterion-related issue](https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options) that I can reproduce locally. The solution given in the FAQ is not working for me, but it's not the concern of `criterion-compare-action`. I'm closing this issue, sorry for the noise.
