### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by smrpn** [boa-dev/criterion-compare-action#21]
```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TLSSocket'
    |     property '_httpMessage' -> object with constructor 'ClientRequest'
    --- property 'socket' closes the circle
    at JSON.stringify (<anonymous>)
    at Object.toCommandValue (/home/runner/work/_actions/boa-dev/criterion-compare-action/master/dist/index.js:1:7497)
    at escapeData (/home/runner/work/_actions/boa-dev/criterion-compare-action/master/dist/index.js:1:3737)
    at Command.toString (/home/runner/work/_actions/boa-dev/criterion-compare-action/master/dist/index.js:1:3668)
    at Object.issueCommand (/home/runner/work/_actions/boa-dev/criterion-compare-action/master/dist/index.js:1:3161)
    at Object.debug (/home/runner/work/_actions/boa-dev/criterion-compare-action/master/dist/index.js:1:5958)
    at main (/home/runner/work/_actions/boa-dev/criterion-compare-action/master/dist/index.js:1:1119)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Unhanded error:
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TLSSocket'
    |     property '_httpMessage' -> object with constructor 'ClientRequest'
    --- property 'socket' closes the circle
```
I'm getting this error. Is this a bug?
ref - https://github.com/smrpn/casbin-rs/pull/2/checks?check_run_id=2268954721

**Comment by Razican** [comment]
Hello @smrpn, are you still getting this issue? I didn't see it in the link.

**Comment by smrpn** [comment]
hey @Razican, it's been almost a year. not working on this bug anymore. don't even remember the issue

**Comment by Razican** [comment]
> hey @Razican, it's been almost a year. not working on this bug anymore. don't even remember the issue

Yes, sorry for the delay, we didn't spend a lot of time working on the action. I will close this for now, but feel free to re-open it again in case you encounter a similar issue. We will be releasing a new version soon.
