### ISSUE TITLE
Unrecognized option: 'save-baseline'

### ISSUE THREAD

**Issue by CastilloDel** [boa-dev/criterion-compare-action#24]
When I try to use this extension, I get the following error:
```
error: Unrecognized option: 'save-baseline'
error: bench failed
Error: The process 'cargo' failed with exit code 101
    at ExecState._setResult (/home/runner/work/_actions/jasonwilliams/criterion-compare-action/move_to_actions/dist/index.js:1:7880)
    at ExecState.CheckComplete (/home/runner/work/_actions/jasonwilliams/criterion-compare-action/move_to_actions/dist/index.js:1:7442)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/jasonwilliams/criterion-compare-action/move_to_actions/dist/index.js:1:6406)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
Error: Unhanded error:
Error: The process 'cargo' failed with exit code 101
```
[CI run](https://github.com/umccr/htsget-rs/pull/59/checks?check_run_id=3314169731)
It seems like it is trying to use an option that doesn't exist.
I tried with criterion 0.3.5 and 0.3.3

**Comment by CastilloDel** [comment]
Related https://github.com/bheisler/criterion.rs/issues/193 Seems like it happens because I also have tests apart from the benchmarks, but it should still work

**Comment by CastilloDel** [comment]
[This workaround](https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options) seems to work. Maybe this should be documented in the README?

**Comment by brainstorm** [comment]
@CastilloDel ... it indeed seems strange because that `-- --save-baseline` is in the `main.js` for this action in:

https://github.com/boa-dev/criterion-compare-action/blob/master/main.js#L37

I'll try to re-run it on our CI and test...

**Comment by Razican** [comment]
`--save-baseline` will only save a local copy of the results of the benchmarks, so it should work. The workaround seems to make sense, maybe we could add it to the README, feel free to open a PR :)
