### ISSUE TITLE
Can't seem to control what branch is compared against

### ISSUE THREAD

**Issue by chipbuster** [boa-dev/criterion-compare-action#29]
My repository uses the nonstandard name "trunk" as the default branch.

When running this action, I see the following output in my Actions logs:

> /usr/bin/git checkout master
> error: pathspec 'master' did not match any file(s) known to git
> Error: The process '/usr/bin/git' failed with exit code 1

The [marketplace site](https://github.com/marketplace/actions/criterion-compare-prs) and the contents of #28 both suggest that I can use the key `branchName` to control this behavior. However, if I try to set this, I get the following warning in the Actions logs:

> Warning: Unexpected input(s) 'branchName', valid inputs are ['token', 'cwd']

and then the Action proceeds to fail in the same way. Is there a way to override this action so that `master` is not the branch that's compared against?

I don't know if it makes a difference, but this is a self-hosted runner with runner software v2.285.0 on Rocky Linux 8.5.

The docs on marketplace seemed to disagree whether the correct name was `boa-dev/criterion-compare-action@v2.0.0` or `jasonwilliams/criterion-compare-action@move_to_actions`. Does this make a difference?

<details>
<summary> Contents of `pull_request.yml` </summary>

```
name: PR Performance check

on: [pull_request]

jobs:
  runBenchmark:
    name: Criterion Compare PRs
    runs-on: [self-hosted, benchmark]
    steps:
      - name: "Enable Cargo"
        run: echo "${HOME}/.cargo/bin" >> $GITHUB_PATH
      - name: "Check PATH"
        run: echo "$PATH"
      - uses: actions/checkout@v2
      - name: Check Against trunk
        uses: boa-dev/criterion-compare-action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branchName: trunk
```
</details>

<details>
<summary> Full GitHub Actions Log of Failed Run </summary>

```
2021-12-07T05:35:35.1499437Z Found online and idle self-hosted runner in the current repository that matches the required labels: 'self-hosted , benchmark'
2021-12-07T05:35:35.1717478Z Waiting for the runner to pick up this job...
2021-12-07T05:35:35.5255468Z Job is about to start running on the runner: ghastly (repository)
2021-12-07T05:35:39.9256382Z Current runner version: '2.285.0'
2021-12-07T05:35:39.9261205Z Runner name: 'ghastly'
2021-12-07T05:35:39.9261847Z Runner group name: 'Default'
2021-12-07T05:35:39.9263098Z Machine name: 'ghastly'
2021-12-07T05:35:39.9266947Z ##[group]GITHUB_TOKEN Permissions
2021-12-07T05:35:39.9268290Z Actions: write
2021-12-07T05:35:39.9268788Z Checks: write
2021-12-07T05:35:39.9269261Z Contents: write
2021-12-07T05:35:39.9269777Z Deployments: write
2021-12-07T05:35:39.9270308Z Discussions: write
2021-12-07T05:35:39.9270798Z Issues: write
2021-12-07T05:35:39.9271271Z Metadata: read
2021-12-07T05:35:39.9271758Z Packages: write
2021-12-07T05:35:39.9272243Z Pages: write
2021-12-07T05:35:39.9272748Z PullRequests: write
2021-12-07T05:35:39.9273360Z RepositoryProjects: write
2021-12-07T05:35:39.9273987Z SecurityEvents: write
2021-12-07T05:35:39.9274582Z Statuses: write
2021-12-07T05:35:39.9275191Z ##[endgroup]
2021-12-07T05:35:39.9278812Z Secret source: Actions
2021-12-07T05:35:39.9279912Z Prepare workflow directory
2021-12-07T05:35:40.0071110Z Prepare all required actions
2021-12-07T05:35:40.0083158Z Getting action download info
2021-12-07T05:35:40.5182088Z Download action repository 'actions/checkout@v2' (SHA:ec3a7ce113134d7a93b817d10a8272cb61118579)
2021-12-07T05:35:41.3638285Z Download action repository 'boa-dev/criterion-compare-action@v2.0.0' (SHA:51d2def841e5e950b6d83e7337baeb13c0bd2b85)
2021-12-07T05:35:44.0420545Z ##[group]Run echo "${HOME}/.cargo/bin" >> $GITHUB_PATH
2021-12-07T05:35:44.0421601Z [36;1mecho "${HOME}/.cargo/bin" >> $GITHUB_PATH[0m
2021-12-07T05:35:44.0439513Z shell: /usr/bin/bash -e {0}
2021-12-07T05:35:44.0440052Z ##[endgroup]
2021-12-07T05:35:44.0572490Z ##[group]Run echo "$PATH"
2021-12-07T05:35:44.0573021Z [36;1mecho "$PATH"[0m
2021-12-07T05:35:44.0591215Z shell: /usr/bin/bash -e {0}
2021-12-07T05:35:44.0591656Z ##[endgroup]
2021-12-07T05:35:44.0653660Z /home/ghactions/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
2021-12-07T05:35:44.0809561Z ##[group]Run actions/checkout@v2
2021-12-07T05:35:44.0810089Z with:
2021-12-07T05:35:44.0810579Z   repository: chipbuster/fast-hampath
2021-12-07T05:35:44.0811650Z   token: ***
2021-12-07T05:35:44.0812051Z   ssh-strict: true
2021-12-07T05:35:44.0812562Z   persist-credentials: true
2021-12-07T05:35:44.0813054Z   clean: true
2021-12-07T05:35:44.0813446Z   fetch-depth: 1
2021-12-07T05:35:44.0813839Z   lfs: false
2021-12-07T05:35:44.0814225Z   submodules: false
2021-12-07T05:35:44.0814727Z ##[endgroup]
2021-12-07T05:35:44.2259176Z Syncing repository: chipbuster/fast-hampath
2021-12-07T05:35:44.2261145Z ##[group]Getting Git version info
2021-12-07T05:35:44.2262898Z Working directory is '/home/ghactions/actions-runner/_work/fast-hampath/fast-hampath'
2021-12-07T05:35:44.2279974Z [command]/usr/bin/git version
2021-12-07T05:35:44.2337402Z git version 2.27.0
2021-12-07T05:35:44.2363934Z ##[endgroup]
2021-12-07T05:35:44.2371849Z [command]/usr/bin/git config --local --get remote.origin.url
2021-12-07T05:35:44.2410562Z https://github.com/chipbuster/fast-hampath
2021-12-07T05:35:44.2422791Z ##[group]Removing previously created refs, to avoid conflicts
2021-12-07T05:35:44.2426868Z [command]/usr/bin/git rev-parse --symbolic-full-name --verify --quiet HEAD
2021-12-07T05:35:44.2463462Z HEAD
2021-12-07T05:35:44.2473376Z [command]/usr/bin/git rev-parse --symbolic-full-name --branches
2021-12-07T05:35:44.2514025Z ##[endgroup]
2021-12-07T05:35:44.2515637Z ##[group]Cleaning the repository
2021-12-07T05:35:44.2518406Z [command]/usr/bin/git clean -ffdx
2021-12-07T05:35:44.2906877Z Removing Cargo.lock
2021-12-07T05:35:44.2907937Z Removing target/
2021-12-07T05:35:44.2915470Z [command]/usr/bin/git reset --hard HEAD
2021-12-07T05:35:44.3001840Z HEAD is now at 573785c Merge 8da67003bb9e8d202f0f76c85e8e3b81c2e0e45a into 61e0e0827e9cfb3fb8005b38a722b6e832936d92
2021-12-07T05:35:44.3004914Z ##[endgroup]
2021-12-07T05:35:44.3008795Z ##[group]Disabling automatic garbage collection
2021-12-07T05:35:44.3011426Z [command]/usr/bin/git config --local gc.auto 0
2021-12-07T05:35:44.3053686Z ##[endgroup]
2021-12-07T05:35:44.3060235Z ##[group]Setting up auth
2021-12-07T05:35:44.3066893Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2021-12-07T05:35:44.3114527Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2021-12-07T05:35:44.3522170Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2021-12-07T05:35:44.3561431Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2021-12-07T05:35:44.3988507Z [command]/usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
2021-12-07T05:35:44.4051435Z ##[endgroup]
2021-12-07T05:35:44.4053017Z ##[group]Fetching the repository
2021-12-07T05:35:44.4055602Z [command]/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +ee5b8027fb7afe36708e1b55454a6ecebb4e8950:refs/remotes/pull/1/merge
2021-12-07T05:35:44.7445451Z remote: Enumerating objects: 12, done.        
2021-12-07T05:35:44.7456531Z remote: Counting objects:   8% (1/12)        
2021-12-07T05:35:44.7457550Z remote: Counting objects:  16% (2/12)        
2021-12-07T05:35:44.7458102Z remote: Counting objects:  25% (3/12)        
2021-12-07T05:35:44.7458651Z remote: Counting objects:  33% (4/12)        
2021-12-07T05:35:44.7459205Z remote: Counting objects:  41% (5/12)        
2021-12-07T05:35:44.7459752Z remote: Counting objects:  50% (6/12)        
2021-12-07T05:35:44.7460318Z remote: Counting objects:  58% (7/12)        
2021-12-07T05:35:44.7460863Z remote: Counting objects:  66% (8/12)        
2021-12-07T05:35:44.7461418Z remote: Counting objects:  75% (9/12)        
2021-12-07T05:35:44.7462600Z remote: Counting objects:  83% (10/12)        
2021-12-07T05:35:44.7463232Z remote: Counting objects:  91% (11/12)        
2021-12-07T05:35:44.7463772Z remote: Counting objects: 100% (12/12)        
2021-12-07T05:35:44.7466863Z remote: Counting objects: 100% (12/12), done.        
2021-12-07T05:35:44.7475075Z remote: Compressing objects:  33% (1/3)        
2021-12-07T05:35:44.7476068Z remote: Compressing objects:  66% (2/3)        
2021-12-07T05:35:44.7476828Z remote: Compressing objects: 100% (3/3)        
2021-12-07T05:35:44.7477610Z remote: Compressing objects: 100% (3/3), done.        
2021-12-07T05:35:44.7479154Z remote: Total 5 (delta 2), reused 3 (delta 1), pack-reused 0        
2021-12-07T05:35:44.7545096Z From https://github.com/chipbuster/fast-hampath
2021-12-07T05:35:44.7550619Z  + 573785c...ee5b802 ee5b8027fb7afe36708e1b55454a6ecebb4e8950 -> pull/1/merge  (forced update)
2021-12-07T05:35:44.7569294Z ##[endgroup]
2021-12-07T05:35:44.7571103Z ##[group]Determining the checkout info
2021-12-07T05:35:44.7572557Z ##[endgroup]
2021-12-07T05:35:44.7573824Z ##[group]Checking out the ref
2021-12-07T05:35:44.7575552Z [command]/usr/bin/git checkout --progress --force refs/remotes/pull/1/merge
2021-12-07T05:35:44.7627490Z Warning: you are leaving 1 commit behind, not connected to
2021-12-07T05:35:44.7628531Z any of your branches:
2021-12-07T05:35:44.7629013Z 
2021-12-07T05:35:44.7630045Z   573785c Merge 8da67003bb9e8d202f0f76c85e8e3b81c2e0e45a into 61e0e0827e9cfb3fb8005b38a722b6e832936d92
2021-12-07T05:35:44.7630990Z 
2021-12-07T05:35:44.7631710Z If you want to keep it by creating a new branch, this may be a good time
2021-12-07T05:35:44.7632456Z to do so with:
2021-12-07T05:35:44.7633471Z 
2021-12-07T05:35:44.7634936Z  git branch <new-branch-name> 573785c
2021-12-07T05:35:44.7635586Z 
2021-12-07T05:35:44.7636672Z HEAD is now at ee5b802 Merge 596a4a66f025580edbdcf6427bb3ac60dc3ff53f into 61e0e0827e9cfb3fb8005b38a722b6e832936d92
2021-12-07T05:35:44.7638624Z ##[endgroup]
2021-12-07T05:35:44.7676086Z [command]/usr/bin/git log -1 --format='%H'
2021-12-07T05:35:44.7726477Z 'ee5b8027fb7afe36708e1b55454a6ecebb4e8950'
2021-12-07T05:35:44.7852180Z ##[warning]Unexpected input(s) 'branchName', valid inputs are ['token', 'cwd']
2021-12-07T05:35:44.7873086Z ##[group]Run boa-dev/criterion-compare-action@v2.0.0
2021-12-07T05:35:44.7873710Z with:
2021-12-07T05:35:44.7875176Z   token: ***
2021-12-07T05:35:44.7875606Z   branchName: trunk
2021-12-07T05:35:44.7876019Z ##[endgroup]
2021-12-07T05:35:44.8594589Z [command]/home/ghactions/.cargo/bin/cargo install critcmp
2021-12-07T05:35:44.9572613Z     Updating crates.io index
2021-12-07T05:35:45.8759845Z      Ignored package `critcmp v0.1.7` is already installed, use --force to override
2021-12-07T05:35:45.8796693Z [command]/home/ghactions/.cargo/bin/cargo bench -- --save-baseline changes
2021-12-07T05:35:46.3711515Z     Updating crates.io index
2021-12-07T05:35:46.8852156Z    Compiling autocfg v1.0.1
2021-12-07T05:35:46.8867109Z    Compiling cfg-if v1.0.0
2021-12-07T05:35:47.0298392Z    Compiling libc v0.2.109
2021-12-07T05:35:47.5136740Z    Compiling lazy_static v1.4.0
2021-12-07T05:35:47.5989996Z    Compiling crossbeam-utils v0.8.5
2021-12-07T05:35:47.6993317Z    Compiling serde v1.0.130
2021-12-07T05:35:48.0026151Z    Compiling semver v1.0.4
2021-12-07T05:35:48.2083540Z    Compiling ryu v1.0.6
2021-12-07T05:35:48.4872017Z    Compiling memchr v2.4.1
2021-12-07T05:35:48.7367977Z    Compiling proc-macro2 v1.0.33
2021-12-07T05:35:48.9239367Z    Compiling crossbeam-epoch v0.9.5
2021-12-07T05:35:49.2991501Z    Compiling scopeguard v1.1.0
2021-12-07T05:35:49.3363023Z    Compiling unicode-xid v0.2.2
2021-12-07T05:35:49.4416539Z    Compiling rayon-core v1.9.1
2021-12-07T05:35:49.5326110Z    Compiling serde_json v1.0.72
2021-12-07T05:35:49.7932395Z    Compiling itoa v0.4.8
2021-12-07T05:35:50.0086478Z    Compiling either v1.6.1
2021-12-07T05:35:50.0148460Z    Compiling ppv-lite86 v0.2.15
2021-12-07T05:35:50.2926871Z    Compiling syn v1.0.82
2021-12-07T05:35:50.5648005Z    Compiling plotters-backend v0.3.2
2021-12-07T05:35:50.8798501Z    Compiling unicode-width v0.1.9
2021-12-07T05:35:51.4183447Z    Compiling regex-automata v0.1.10
2021-12-07T05:35:51.4255823Z    Compiling serde_derive v1.0.130
2021-12-07T05:35:51.5160744Z    Compiling half v1.8.2
2021-12-07T05:35:51.7463574Z    Compiling bitflags v1.3.2
2021-12-07T05:35:51.8747667Z    Compiling typed-arena v2.0.1
2021-12-07T05:35:52.0736914Z    Compiling regex-syntax v0.6.25
2021-12-07T05:35:52.5262231Z    Compiling same-file v1.0.6
2021-12-07T05:35:52.8686061Z    Compiling oorandom v11.1.3
2021-12-07T05:35:53.1023712Z    Compiling memoffset v0.6.5
2021-12-07T05:35:53.5976399Z    Compiling num-traits v0.2.14
2021-12-07T05:35:53.9536337Z    Compiling rayon v1.5.1
2021-12-07T05:35:55.0429176Z    Compiling itertools v0.10.3
2021-12-07T05:35:57.5958477Z    Compiling plotters-svg v0.3.1
2021-12-07T05:35:58.3715437Z    Compiling textwrap v0.11.0
2021-12-07T05:35:59.6600999Z    Compiling walkdir v2.3.2
2021-12-07T05:36:01.5723410Z    Compiling regex v1.5.4
2021-12-07T05:36:13.8882957Z    Compiling clap v2.34.0
2021-12-07T05:36:15.6016244Z    Compiling getrandom v0.2.3
2021-12-07T05:36:16.0892550Z    Compiling num_cpus v1.13.0
2021-12-07T05:36:17.7205574Z    Compiling atty v0.2.14
2021-12-07T05:36:17.8696033Z    Compiling crossbeam-channel v0.5.1
2021-12-07T05:36:19.2936278Z    Compiling rustc_version v0.4.0
2021-12-07T05:36:25.3777745Z    Compiling serde_cbor v0.11.2
2021-12-07T05:36:28.0075751Z    Compiling bstr v0.2.17
2021-12-07T05:36:30.3450204Z    Compiling csv-core v0.1.10
2021-12-07T05:36:31.3752402Z    Compiling quote v1.0.10
2021-12-07T05:36:33.2225839Z    Compiling plotters v0.3.1
2021-12-07T05:36:36.0368115Z    Compiling rand_core v0.6.3
2021-12-07T05:36:36.5523271Z    Compiling cast v0.2.7
2021-12-07T05:36:36.9345691Z    Compiling tinytemplate v1.2.1
2021-12-07T05:36:40.3462221Z    Compiling csv v1.1.6
2021-12-07T05:36:43.1256341Z    Compiling crossbeam-deque v0.8.1
2021-12-07T05:36:43.4001542Z    Compiling rand_chacha v0.3.1
2021-12-07T05:36:47.1505649Z    Compiling rand v0.8.4
2021-12-07T05:36:52.2435990Z    Compiling fast-hampath v0.1.0 (/home/ghactions/actions-runner/_work/fast-hampath/fast-hampath)
2021-12-07T05:36:53.9627807Z    Compiling criterion-plot v0.4.4
2021-12-07T05:36:56.1735846Z    Compiling criterion v0.3.5
2021-12-07T05:37:30.0682838Z     Finished bench [optimized] target(s) in 1m 44s
2021-12-07T05:37:30.0799536Z      Running unittests (target/release/deps/time_benchmarks-347e97521a69467d)
2021-12-07T05:37:30.0830315Z WARNING: HTML report generation will become a non-default optional feature in Criterion.rs 0.4.0.
2021-12-07T05:37:30.0833243Z This feature is being moved to cargo-criterion (https://github.com/bheisler/cargo-criterion) and will be optional in a future version of Criterion.rs. To silence this warning, either switch to cargo-criterion or enable the 'html_reports' feature in your Cargo.toml.
2021-12-07T05:37:30.0835082Z 
2021-12-07T05:37:30.0835899Z Gnuplot not found, using plotters backend
2021-12-07T05:37:30.1361648Z Benchmarking solve n=100
2021-12-07T05:37:30.1362307Z Benchmarking solve n=100: Warming up for 3.0000 s
2021-12-07T05:37:35.3789702Z Benchmarking solve n=100: Collecting 100 samples in estimated 5.1299 s (500 iterations)
2021-12-07T05:37:40.5085700Z Benchmarking solve n=100: Analyzing
2021-12-07T05:37:40.9106389Z solve n=100             time:   [10.258 ms 10.259 ms 10.260 ms]
2021-12-07T05:37:40.9107119Z Found 9 outliers among 100 measurements (9.00%)
2021-12-07T05:37:40.9110185Z   1 (1.00%) low severe
2021-12-07T05:37:40.9123111Z   7 (7.00%) low mild
2021-12-07T05:37:40.9135889Z   1 (1.00%) high severe
2021-12-07T05:37:44.9674501Z 
2021-12-07T05:37:44.9734477Z [command]/usr/bin/git checkout master
2021-12-07T05:37:44.9771296Z error: pathspec 'master' did not match any file(s) known to git
2021-12-07T05:37:44.9785989Z Error: The process '/usr/bin/git' failed with exit code 1
2021-12-07T05:37:44.9787926Z     at ExecState._setResult (/home/ghactions/actions-runner/_work/_actions/boa-dev/criterion-compare-action/v2.0.0/dist/index.js:1:12035)
2021-12-07T05:37:44.9790193Z     at ExecState.CheckComplete (/home/ghactions/actions-runner/_work/_actions/boa-dev/criterion-compare-action/v2.0.0/dist/index.js:1:11597)
2021-12-07T05:37:44.9802910Z     at ChildProcess.<anonymous> (/home/ghactions/actions-runner/_work/_actions/boa-dev/criterion-compare-action/v2.0.0/dist/index.js:1:10445)
2021-12-07T05:37:44.9804501Z     at ChildProcess.emit (events.js:314:20)
2021-12-07T05:37:44.9805400Z     at maybeClose (internal/child_process.js:1022:16)
2021-12-07T05:37:44.9806298Z     at Socket.<anonymous> (internal/child_process.js:444:11)
2021-12-07T05:37:44.9807479Z     at Socket.emit (events.js:314:20)
2021-12-07T05:37:44.9815225Z     at Pipe.<anonymous> (net.js:675:12)
2021-12-07T05:37:44.9821034Z ##[error]Unhanded error:
Error: The process '/usr/bin/git' failed with exit code 1
2021-12-07T05:37:44.9925629Z Post job cleanup.
2021-12-07T05:37:45.1236188Z [command]/usr/bin/git version
2021-12-07T05:37:45.1297427Z git version 2.27.0
2021-12-07T05:37:45.1338764Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2021-12-07T05:37:45.1386215Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2021-12-07T05:37:45.1792230Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2021-12-07T05:37:45.1845701Z http.https://github.com/.extraheader
2021-12-07T05:37:45.1866718Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2021-12-07T05:37:45.1884290Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2021-12-07T05:37:45.2340273Z Cleaning up orphan processes
```
</details>

**Comment by Razican** [comment]
Hmmm this might be due to the latest version in the `master` branch being unreleased. I will make sure to release a new version in the marketplace and let you know.
